In [ ]:
import pandas as pd
df = pd.read_csv('C:\\Users\\Heleno\\Documents\\Projetos Portifólio\\saude_publica_analysis\\data\\World_Development_Indicators.csv')


# Exibir as primeiras linhas para entender a estrutura do dataset
print(df.head())
print(df.isnull().sum())
print(df.dtypes)

In [39]:
def clean_data(df):
    # Excluir colunas irrelevantes
    df = df.drop(columns=['Country Code', 'Series Code'])

    df.rename(columns={'2017 [YR2017]': 'YR_2017', '2018 [YR2018]': 'YR_2018', '2019 [YR2019]': 'YR_2019', 
                       '2020 [YR2020]': 'YR_2020', '2021 [YR2021]': 'YR_2021', '2022 [YR2022]': 'YR_2022', 
                       '2023 [YR2023]': 'YR_2023'}, inplace=True)

    for year in range(2017, 2024):
        column_name = f'YR_{year}'
        df[column_name] = pd.to_numeric(df[column_name], errors='coerce')  # Converte e substitui NaN por não numéricos
        
    # Preencher valores faltantes com a média da coluna (apenas para colunas numéricas)
    for column in df.select_dtypes(include=['float64', 'int64']).columns:
        df[column].fillna(df[column].mean())



    
    return df  # Retorne o DataFrame modificado


# Carregue o DataFrame
df = pd.read_csv('C:\\Users\\Heleno\\Documents\\Projetos Portifólio\\saude_publica_analysis\\data\\World_Development_Indicators.csv')

# Limpe os dados e armazene o resultado em uma nova variável
df_cleaned = clean_data(df)

# Visualize as primeiras linhas da nova tabela
df_cleaned.head()

,Country Name,Series Name,YR_2017,YR_2018,YR_2019,YR_2020,YR_2021,YR_2022,YR_2023
0,Argentina,"Adolescent fertility rate (births per 1,000 wo...",57.783000,51.029000,46.153000,39.866000,39.065000,37.932000,NaN
1,Argentina,"Agriculture, forestry, and fishing, value adde...",5.231622,4.537879,5.318556,6.357034,7.306309,6.639898,6.059509
2,Argentina,"Annual freshwater withdrawals, total (% of int...",12.907534,12.907534,12.907534,12.907534,NaN,NaN,NaN
3,Argentina,Births attended by skilled health staff (% of ...,93.900000,99.500000,99.600000,98.800000,NaN,NaN,NaN
4,Argentina,CO2 emissions (metric tons per capita),4.070112,3.975651,3.742030,3.405618,NaN,NaN,NaN

Country Name     object
YR_2017         float64
YR_2018         float64
YR_2019         float64
YR_2020         float64
YR_2021         float64
YR_2022         float64
YR_2023         float64
dtype: object